CREATE TABLE FILM(
   ID SERIAL PRIMARY KEY     NOT NULL,
   NAME           CHAR(100)    NOT NULL,
   DIRECTOR           CHAR(40)    NOT NULL,
   CREATIONDATE DATE NOT NULL default CURRENT_DATE,
   RELEASEDATE          DATE   NOT NULL,
   GENRE           CHAR(30)    NOT NULL,
   DESCRIPTION           VARCHAR(500)    NOT NULL,
   LENGTH           INT NOT NULL,
   SUMCOMMENTS INT DEFAULT 0,
   TOTALCOMMENTS INT DEFAULT 0
);

CREATE TABLE GAJAMDBUSER(
	ID SERIAL 	 PRIMARY KEY  NOT NULL,
	EMAIL           CHAR(40)    NOT NULL,
	PASSWORD           CHAR(10)    NOT NULL,
	NAME           CHAR(15)    NOT NULL,
	LASTNAME            CHAR(15)    NOT NULL,
 	BIRTHDATE          DATE   NOT NULL,
  SECRETQUESTION VARCHAR(140) NOT NULL,
  SECRETANSWER VARCHAR(140) NOT NULL,       
  VIP 			BOOLEAN NOT NULL,
  UNIQUE(EMAIL)
);

CREATE TABLE COMMENT(
   ID SERIAL PRIMARY KEY     NOT NULL,
   FILM_ID INT references FILM(ID) ON DELETE CASCADE ,
   USER_ID INT references GAJAMDBUSER(ID) ON DELETE CASCADE ,
   TEXT           CHAR(140)    NOT NULL,
   RATE           INT    NOT NULL
);