CREATE TABLE FILM(
   ID SERIAL PRIMARY KEY     NOT NULL,
   NAME           VARCHAR(100)    NOT NULL,
   DIRECTOR           VARCHAR(40)    NOT NULL,
   CREATIONDATE DATE NOT NULL default CURRENT_DATE,
   RELEASEDATE          DATE   NOT NULL,
   GENRE           VARCHAR(30)    NOT NULL,
   DESCRIPTION           VARCHAR(500)    NOT NULL,
   LENGTH           INT NOT NULL,
   SUMCOMMENTS INT DEFAULT 0,
   TOTALCOMMENTS INT DEFAULT 0
);

CREATE TABLE GAJAMDBUSER(
	ID SERIAL 	 PRIMARY KEY  NOT NULL,
	EMAIL           VARCHAR(100)    NOT NULL,
	PASSWORD           VARCHAR(10)    NOT NULL,
	NAME           VARCHAR(15)    NOT NULL,
	LASTNAME            VARCHAR(15)    NOT NULL,
 	BIRTHDATE          DATE   NOT NULL,
  SECRETQUESTION VARCHAR(140) NOT NULL,
  SECRETANSWER VARCHAR(140) NOT NULL,       
  VIP 			BOOLEAN NOT NULL,
  UNIQUE(EMAIL)
);

CREATE TABLE COMMENT(
   ID SERIAL PRIMARY KEY     NOT NULL,
   FILM_ID INT references FILM(ID) ON DELETE CASCADE ,
   USER_ID INT references GAJAMDBUSER(ID) ON DELETE CASCADE ,
   CREATIONDATE TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
   TEXT           VARCHAR(140)    NOT NULL,
   RATE           INT    NOT NULL,
   UNIQUE(FILM_ID,USER_ID)
);