CREATE TABLE FILM(
   ID SERIAL PRIMARY KEY     NOT NULL,
   NAME           CHAR(100)    NOT NULL,
   DIRECTOR           CHAR(30)    NOT NULL,
   RELEASEDATE          DATE   NOT NULL,
   GENRE           CHAR(30)    NOT NULL,
   DESCRIPTION           CHAR(300)    NOT NULL
);

CREATE TABLE GAJAMDBUSER(
	ID SERIAL 	 PRIMARY KEY  NOT NULL,
	MAIL           CHAR(30)    NOT NULL,
	PASSWORD           CHAR(10)    NOT NULL,
	NAME           CHAR(15)    NOT NULL,
	LASTNAME            CHAR(15)    NOT NULL,
 	BIRTHDAY          DATE   NOT NULL,       
    VIP 			BOOLEAN NOT NULL,
    UNIQUE(MAIL)
);

CREATE TABLE COMMENT(
   ID SERIAL PRIMARY KEY     NOT NULL,
   FILM_ID INT references FILM(ID),
   USER_ID INT references GAJAMDBUSER(ID),
   TEXT           CHAR(140)    NOT NULL,
   RATE           INT    NOT NULL
);